### ISSUE TITLE
error by starting shortcut

### ISSUE THREAD

**Issue by andelwol26** [atidot3/GameLauncher#6]
Hello,

i found a new error which is appering by starting a shortcut with the Lanucher.
This error only appering when the Shortcut is placed on "C:\Program Files\".
When i change the shortcut to "C:\Programme" (German expression) it works. 

The error is telling that the File could not be found. 
Screenshot of the error: https://imgur.com/a/JIjKcXQ

**Comment by atidot3** [comment]
i think the issue here is related to hardcoded path in the solution.
```
private void backgroundWorker1_DoWork(object sender, DoWorkEventArgs e)
        {
            string path = System.IO.Path.GetFullPath("./");
            ....
        }
```

The best solution would be to make a config file with the launcher location.

```
string path = config.launcher_path;

launcher_path = "C:\...
```
