### ISSUE TITLE
Microsoft is removing IE11

### ISSUE THREAD

**Issue by andelwol26** [atidot3/GameLauncher#7]
microsoft is removing ie11 completly from the computers. Links don't work in the launcher after uninstalling ie11.
How could we fix that?

**Comment by atidot3** [comment]
The simplest solution is to add a Web Form to your project, and then right-click that. There you have a "Browse with" option. After setting the default browser, you can remove the Web Form from your project again.

I agree this is a clumsy work-around. It ought to be simply possible to select a browser when debugging an MVC project.

It does seem like Microsoft is considering this for a future version.
